### ISSUE TITLE
UI_DEV_SETUP check not working properly?

### ISSUE THREAD

**Issue by yuyuyak** [Blub/netevent#2]
Hi.  Have been using stable-1 for months, wonderful!
But I do like the simplicity of the new version.  However when I try to run it I always get
error: failed to setup uinput device: Invalid argument
I've traced this back to the fact that my remote machine is stuck on kernel 3.10 (they promise someday to merge into mainline, you know) and the ioctl stuff just isn't there.  When I run configure I see
Checking for UI_DEV_SETUP (kernel >= 4.4)
But it seems as if it just assumes it is present.
I'm quite happy with stable-1 forever, but I thought you might like to know of this issue.

**Comment by yuyuyak** [comment]
Oh, so simple.  I just deleted #define HAS_UI_DEV_SETUP from config.h and it works fine.
So it's only the check that is failing.

**Comment by yuyuyak** [comment]
More info as I don't want to cause you unnecessary grief.  Looking thru the configure program I see that it examines linux/uinput.h to determine the presence/absence of the UI_DEV_SETUP ioctls.  In my linux/uinput.h it is mentioned.  But this file comes from userspace, not the kernel, specifically a Funtoo package called sys-kernel/linux-headers-4.9.  In /usr/src/linux/include/linux/uinput.h there is no mention of UI_DEV_SETUP, it's the older (correct) version for this 3.10 kernel.  I've always been very confused about this issue, as the Funtoo linux-headers package is part of a normal installation, but I have used it for > 2 years, over a year of that my only computer! (odroid C1+) and this is the 1st time I've had any issue with it that I'm aware of.  So apparently this is a local issue and not the fault of your configure.

**Comment by Blub** [comment]
One alternative would be for the configure script to actually try and run/use it, but I didn't feel like creating a uinput device during a `./configure` was a "clean" solution.
But the best way would probably be to just compile in both versions and handle an `Invalid argument` error on the `ioctl` at runtime and then fall back to the old way.

**Comment by yuyuyak** [comment]
Perhaps you're right.  I researched this issue tonight as it has bothered me for a long time, and according to both the Gentoo wiki [https://wiki.gentoo.org/wiki/Linux-headers](url) and a link they have there to a message from Linus Torvalds it is proper to have headers that don't match the kernel.  Crazy.
A  thought I had was just to detect the actual kernel version with uname -r, I don't know how all-encompassing that would be.  Or simply have a manual configuration option for corner cases like this like --no-ui-dev-setup.

**Comment by Blub** [comment]
I'm not opposed to adding a configure option. Catching the `Invalid argument` error at runtime as well. Detecting the kernel version on the other hand is not always the best choice since, for example, there's no guarantee some LTS kernel might not get something backported in which case you have that available in an old and new kernel but not in-between. (In this case this is unlikely, but as a general rule of thumb it's better to detect the feature directly rather than guessing it from some version ;-)
As for the headers - in this case the header is usually shipped with libc, but the feature isn't wrapped by it, iow. there's no library in use, but the ioctl() goes directly to the kernel, making this a somewhat tricky situation.
